#!/usr/bin/env tsx
/**
 * Reads compiled recipe JSONs from scripts/output/ and regenerates:
 *   src/data/legendary-armors.ts
 *   src/data/legendary-weapons.ts
 *
 * Usage:
 *   npm run generate:data
 *
 * Run after the relevant compile:* scripts.
 */

import fs   from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname   = path.dirname(fileURLToPath(import.meta.url))
const OUTPUT_DIR  = path.join(__dirname, 'output')
const SRC_DATA    = path.join(__dirname, '..', 'src', 'data')

interface MaterialNode {
  name: string
  quantity?: number
  itemId?: number
  source?: string
  note?: string
  children?: MaterialNode[]
}

interface CompiledItem {
  itemId: number
  name: string
  type: 'armor' | 'weapon'
  setKey: string
  slot?: string
  weightClass?: string
  rarity: string
  components: MaterialNode[]
  _meta: { generatedAt: string; recipeSource: string }
}

// ── Set configuration ─────────────────────────────────────────────────────────

interface ArmorSetConfig {
  subtype: string
  idPrefix: string
  /** Which weight class to use as the representative for display; falls back to first found */
  preferWeight: string
}

const ARMOR_SETS: Record<string, ArmorSetConfig> = {
  envoy:      { subtype: 'Raid (Envoy)',  idPrefix: 'envoy-armor',     preferWeight: 'Heavy' },
  obsidian:   { subtype: 'Obsidian',      idPrefix: 'obsidian-armor',  preferWeight: 'Heavy' },
  mistforged: { subtype: 'Mistforged',    idPrefix: 'mistforged-armor',preferWeight: 'Heavy' },
}

const WEAPON_SETS: Record<string, { subtype: string }> = {
  gen1: { subtype: 'Gen 1' },
}

const SLOT_ORDER = ['Helm', 'Shoulders', 'Chest', 'Gloves', 'Leggings', 'Boots']

// ── Serialization helpers ─────────────────────────────────────────────────────

function scaleNode(node: MaterialNode, factor: number): MaterialNode {
  return {
    ...node,
    quantity: node.quantity !== undefined ? node.quantity * factor : undefined,
    children: node.children?.map(c => scaleNode(c, factor)),
  }
}

function nodeToTS(node: MaterialNode, depth: number): string {
  const pad  = '  '.repeat(depth)
  const pad1 = '  '.repeat(depth + 1)
  const lines: string[] = [`${pad}{`]
  lines.push(`${pad1}name: ${JSON.stringify(node.name)},`)
  if (node.quantity !== undefined) lines.push(`${pad1}quantity: ${node.quantity},`)
  if (node.itemId   !== undefined) lines.push(`${pad1}itemId: ${node.itemId},`)
  if (node.source)                 lines.push(`${pad1}source: ${JSON.stringify(node.source)},`)
  if (node.note)                   lines.push(`${pad1}note: ${JSON.stringify(node.note)},`)
  if (node.children?.length) {
    lines.push(`${pad1}children: [`)
    for (const child of node.children) lines.push(nodeToTS(child, depth + 2) + ',')
    lines.push(`${pad1}],`)
  }
  lines.push(`${pad}}`)
  return lines.join('\n')
}

// ── File loading ──────────────────────────────────────────────────────────────

function loadAll(): CompiledItem[] {
  if (!fs.existsSync(OUTPUT_DIR)) return []
  return fs.readdirSync(OUTPUT_DIR)
    .filter(f => f.endsWith('.json'))
    .map(f => JSON.parse(fs.readFileSync(path.join(OUTPUT_DIR, f), 'utf-8')) as CompiledItem)
    .filter(d => d.setKey) // must have a setKey (older compiled files without it are skipped)
}

// ── Armor generation ──────────────────────────────────────────────────────────

function generateArmors(items: CompiledItem[]): string {
  const armors = items.filter(d => d.type === 'armor')
  const out: string[] = [
    `// AUTO-GENERATED by scripts/generate-data.ts — do not edit by hand`,
    `// Source: gw2efficiency API + GW2 official API`,
    `// Regenerate: npm run compile:legendary && npm run generate:data`,
    `import type { LegendaryItem } from '../types'`,
    ``,
    `export const LEGENDARY_ARMORS: LegendaryItem[] = [`,
  ]

  let totalEntries = 0

  for (const [setKey, cfg] of Object.entries(ARMOR_SETS)) {
    const setPieces = armors.filter(a => a.setKey === setKey)
    if (!setPieces.length) continue

    // Use preferWeight class; fall back to whatever is available
    const preferredPieces = setPieces.filter(a => a.weightClass === cfg.preferWeight)
    const pieces = (preferredPieces.length ? preferredPieces : setPieces)
      .sort((a, b) => SLOT_ORDER.indexOf(a.slot ?? '') - SLOT_ORDER.indexOf(b.slot ?? ''))

    if (!pieces.length) continue

    // ── Full Set ──
    // component[0] = slot-specific piece (Arcanum/Refined Envoy/etc.) — unique per slot
    // component[1..] = shared gifts — aggregate by itemId across all 6 slots because
    // some sets (e.g. Obsidian) use different component[3] for upper vs lower armor.

    // Aggregate gifts: key = itemId (or fallback to name), value = node with summed qty
    const giftMap = new Map<string, MaterialNode>()
    for (const piece of pieces) {
      for (const gift of piece.components.slice(1)) {
        const key = String(gift.itemId ?? gift.name)
        const existing = giftMap.get(key)
        if (existing) {
          existing.quantity = (existing.quantity ?? 1) + (gift.quantity ?? 1)
        } else {
          giftMap.set(key, { ...gift })
        }
      }
    }

    const fullSetIds = pieces.map(p => p.itemId)

    out.push(`  // ── ${cfg.subtype} — Full Set ─────────────────────────────────────────────`)
    out.push(`  {`)
    out.push(`    id: ${JSON.stringify(`${cfg.idPrefix}-full-set`)},`)
    out.push(`    name: 'Full Set (6 pieces)',`)
    out.push(`    type: 'armor',`)
    out.push(`    subtype: ${JSON.stringify(cfg.subtype)},`)
    out.push(`    isFullSet: true,`)
    out.push(`    legendaryItemIds: [${fullSetIds.join(', ')}],`)
    out.push(`    components: [`)
    for (const piece of pieces) out.push(nodeToTS(piece.components[0], 3) + ',')
    for (const gift of giftMap.values()) out.push(nodeToTS(gift, 3) + ',')
    out.push(`    ],`)
    out.push(`  },`)
    totalEntries++

    // ── Individual slots ──
    for (const piece of pieces) {
      const slotId = (piece.slot ?? piece.name).toLowerCase()
      out.push(`  // ${cfg.subtype} — ${piece.slot}`)
      out.push(`  {`)
      out.push(`    id: ${JSON.stringify(`${cfg.idPrefix}-${slotId}`)},`)
      out.push(`    name: ${JSON.stringify(piece.slot ?? piece.name)},`)
      out.push(`    type: 'armor',`)
      out.push(`    subtype: ${JSON.stringify(cfg.subtype)},`)
      out.push(`    legendaryItemIds: [${piece.itemId}],`)
      out.push(`    components: [`)
      for (const comp of piece.components) out.push(nodeToTS(comp, 3) + ',')
      out.push(`    ],`)
      out.push(`  },`)
      totalEntries++
    }
  }

  out.push(`]`)
  out.push(``)
  return out.join('\n')
}

// ── Weapons generation ────────────────────────────────────────────────────────

function generateWeapons(items: CompiledItem[]): string {
  const weapons = items.filter(d => d.type === 'weapon')
  const out: string[] = [
    `// AUTO-GENERATED by scripts/generate-data.ts — do not edit by hand`,
    `// Source: gw2efficiency API + GW2 official API`,
    `// Regenerate: npm run compile:legendary:weapons && npm run generate:data`,
    `import type { LegendaryItem } from '../types'`,
    ``,
    `export const LEGENDARY_WEAPONS: LegendaryItem[] = [`,
  ]

  let totalEntries = 0

  for (const [setKey, cfg] of Object.entries(WEAPON_SETS)) {
    const setWeapons = weapons
      .filter(w => w.setKey === setKey)
      .sort((a, b) => a.name.localeCompare(b.name))

    if (!setWeapons.length) continue

    for (const weapon of setWeapons) {
      const idSlug = weapon.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/-+$/,'')
      out.push(`  // ${weapon.name} (${weapon.slot ?? 'Weapon'})`)
      out.push(`  {`)
      out.push(`    id: ${JSON.stringify(`${setKey}-${idSlug}`)},`)
      out.push(`    name: ${JSON.stringify(weapon.name)},`)
      out.push(`    type: 'weapon',`)
      out.push(`    subtype: ${JSON.stringify(cfg.subtype)},`)
      out.push(`    legendaryItemIds: [${weapon.itemId}],`)
      out.push(`    components: [`)
      for (const comp of weapon.components) out.push(nodeToTS(comp, 3) + ',')
      out.push(`    ],`)
      out.push(`  },`)
      totalEntries++
    }
  }

  out.push(`]`)
  out.push(``)
  return out.join('\n')
}

// ── Main ──────────────────────────────────────────────────────────────────────

function main() {
  const all = loadAll()
  if (!all.length) {
    console.error('No compiled JSONs with setKey found in scripts/output/.')
    console.error('Run the relevant compile:* scripts first.')
    process.exit(1)
  }

  const armorsTS  = generateArmors(all)
  const weaponsTS = generateWeapons(all)

  const armorsFile  = path.join(SRC_DATA, 'legendary-armors.ts')
  const weaponsFile = path.join(SRC_DATA, 'legendary-weapons.ts')

  fs.writeFileSync(armorsFile,  armorsTS,  'utf-8')
  fs.writeFileSync(weaponsFile, weaponsTS, 'utf-8')

  const armorCount  = all.filter(d => d.type === 'armor').length
  const weaponCount = all.filter(d => d.type === 'weapon').length

  console.log(`✓ ${path.relative(process.cwd(), armorsFile)}`)
  console.log(`  ${armorCount} armor pieces across sets: ${Object.keys(ARMOR_SETS).filter(k => all.some(d => d.setKey === k)).join(', ')}`)
  console.log(`✓ ${path.relative(process.cwd(), weaponsFile)}`)
  console.log(`  ${weaponCount} weapons across sets: ${Object.keys(WEAPON_SETS).filter(k => all.some(d => d.setKey === k)).join(', ')}`)
}

main()
